# Generated by Django 2.0.5 on 2018-08-09 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('state', models.CharField(default='initial', max_length=30)),
                ('is_finished', models.BooleanField(default=False)),
                ('jwt_token', models.CharField(max_length=700, null=True)),
                ('refresh_token', models.CharField(max_length=750, null=True)),
                ('last_auth', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 11, 29, 40, 859452), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('saved_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareSupport',
            fields=[
                ('workitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hangouts.WorkItem')),
                ('hardware_type', models.CharField(choices=[('Internet/Wifi', 'Internet/Wifi'), ('Laptop/Computer', 'Laptop/Computer'), ('Mobile Device', 'Mobile Device'), ('Other', 'Other'), ('Printer', 'Printer')], max_length=30)),
                ('severity', models.IntegerField(choices=[(1, '1 - Critical'), (2, '2 - High'), (3, '3 - Medium'), (4, '4 - Low')], default=3)),
            ],
            bases=('hangouts.workitem',),
        ),
        migrations.CreateModel(
            name='SoftwareSupport',
            fields=[
                ('workitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hangouts.WorkItem')),
                ('requested_by', models.TextField()),
                ('third_party', models.CharField(max_length=30)),
                ('severity', models.IntegerField(choices=[(1, '1 - Critical'), (2, '2 - High'), (3, '3 - Medium'), (4, '4 - Low')], default=3)),
            ],
            bases=('hangouts.workitem',),
        ),
        migrations.AddField(
            model_name='user',
            name='work_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangouts.WorkItem'),
        ),
    ]
