# Generated by Django 2.0.5 on 2018-07-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
