# Generated by Django 2.0.5 on 2018-07-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0002_auto_20180723_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
