# Generated by Django 2.0.5 on 2018-08-09 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0002_auto_20180809_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_auth',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 11, 52, 45, 345916), null=True),
        ),
    ]
