# Generated by Django 2.0.5 on 2018-07-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0003_auto_20180723_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='initial', max_length=30),
        ),
    ]
