# Generated by Django 2.0.5 on 2018-08-09 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0003_auto_20180809_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaresupport',
            name='severity',
            field=models.CharField(choices=[('1 - Critical', '1 - Critical'), ('2 - High', '2 - High'), ('3 - Medium', '3 - Medium'), ('4 - Low', '4 - Low')], default='3 - Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='softwaresupport',
            name='severity',
            field=models.CharField(choices=[('1 - Critical', '1 - Critical'), ('2 - High', '2 - High'), ('3 - Medium', '3 - Medium'), ('4 - Low', '4 - Low')], default='3 - Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_auth',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 11, 55, 34, 777561), null=True),
        ),
    ]
