# Generated by Django 2.0.5 on 2018-07-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0004_auto_20180723_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaresupport',
            name='severity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='softwaresupport',
            name='severity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
