# Generated by Django 2.0.5 on 2018-07-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0005_auto_20180724_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hangouts.WorkItem'),
        ),
    ]
