# Generated by Django 2.0.5 on 2018-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0006_auto_20180724_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
