# Generated by Django 2.0.5 on 2018-07-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0007_user_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaresupport',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
