# Generated by Django 2.0.5 on 2018-07-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0008_auto_20180725_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaresupport',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
