# Generated by Django 2.0.5 on 2018-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0009_auto_20180725_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vstsarea',
            name='hangoutsSpaces',
        ),
        migrations.AlterField(
            model_name='softwaresupport',
            name='requested_by',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='VstsArea',
        ),
    ]
