# Generated by Django 2.0.5 on 2018-08-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0010_auto_20180731_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemCreated',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangouts.User')),
            ],
        ),
    ]
