# Generated by Django 2.0.5 on 2018-08-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0015_auto_20180803_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_auth',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
