# Generated by Django 2.0.5 on 2018-08-06 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0016_auto_20180803_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_auth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 6, 5, 59, 48, 991992)),
        ),
    ]
