# Generated by Django 2.0.5 on 2018-08-09 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0017_auto_20180806_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='saved_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hardwaresupport',
            name='hardware_type',
            field=models.CharField(choices=[('Internet/Wifi', 'Internet/Wifi'), ('Laptop/Computer', 'Laptop/Computer'), ('Mobile Device', 'Mobile Device'), ('Other', 'Other'), ('Printer', 'Printer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hardwaresupport',
            name='severity',
            field=models.IntegerField(choices=[(1, '1 - Critical'), (2, '2 - High'), (3, '3 - Medium'), (4, '4 - Low')], default='3 - Medium'),
        ),
        migrations.AlterField(
            model_name='softwaresupport',
            name='severity',
            field=models.IntegerField(choices=[(1, '1 - Critical'), (2, '2 - High'), (3, '3 - Medium'), (4, '4 - Low')], default='3 - Medium'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_auth',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 10, 31, 33, 84708), null=True),
        ),
    ]
