# Generated by Django 2.0.5 on 2018-08-09 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0018_auto_20180809_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaresupport',
            name='severity',
            field=models.CharField(choices=[(1, '1 - Critical'), (2, '2 - High'), (3, '3 - Medium'), (4, '4 - Low')], default='3 - Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_auth',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 10, 43, 33, 141222), null=True),
        ),
    ]
