# Generated by Django 2.0.5 on 2018-08-09 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0019_auto_20180809_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaresupport',
            name='severity',
            field=models.IntegerField(choices=[(1, '1 - Critical'), (2, '2 - High'), (3, '3 - Medium'), (4, '4 - Low')], default='3'),
        ),
        migrations.AlterField(
            model_name='softwaresupport',
            name='severity',
            field=models.IntegerField(choices=[(1, '1 - Critical'), (2, '2 - High'), (3, '3 - Medium'), (4, '4 - Low')], default='3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_auth',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 11, 8, 59, 217971), null=True),
        ),
    ]
